name: SurvivalTools
version: 1.0.0
main: me.ryanlauderbach.survivaltools.SurvivalTools
api-version: 1.21
author: Ryan
description: Tools for survival worlds

commands:
  home:
    description: Teleports you to your spawnpoint
  find:
    description: Makes the player in question glow
  tpa:
    description: Requests to teleport you to a player
  ping:
    description: Shows the ping of a player
  invsee:
    description: Opens another players inventory